name: Test archive

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    permissions:
      contents: write
    steps:
    - name: "Checkout source code"
      uses: actions/checkout@v3
      with:
        ref: "${{ env.commitsha }}"

    - name: Read the RELEASE_VERSION file
      id: getversion
      run: echo "version=$(cat RELEASE_VERSION)" >> $GITHUB_OUTPUT

    - uses: actions/setup-node@v3
      with:
        node-version: '18.17.0'
        registry-url: 'https://registry.npmjs.org'

    - name: Build common library
      working-directory: ./Common
      run: npm ci && npm run build

    - name: Build frontend library
      working-directory: ./Frontend/library
      run: npm ci && npm link ../../Common && npm run build

    - name: Build frontend ui-library
      working-directory: ./Frontend/ui-library
      run: npm ci && npm link ../library && npm run build

    - name: Install implementations/typescript deps
      working-directory: ./Frontend/implementations/typescript
      run: npm ci && npm link ../../library ../../ui-library && npm run build

    - name: Move all content into output directory for archiving
      run: items=(*) && mkdir PixelStreamingInfrastructure-${{ github.ref_name }}-${{ steps.getversion.outputs.version }} && mv ${items[*]} PixelStreamingInfrastructure-${{ github.ref_name }}-${{ steps.getversion.outputs.version }}/

    - name: Archive Release tar.gz
      uses: thedoctor0/zip-release@0.7.1
      with:
        directory: '.'
        path: 'PixelStreamingInfrastructure-${{ github.ref_name }}-${{ steps.getversion.outputs.version }}'
        type: 'tar'
        filename: '${{ github.ref_name }}-${{ steps.getversion.outputs.version }}.tar.gz'
        exclusions: >-
          .git
          .github
          output
          Common/build
          Common/docs
          Common/node_modules
          Docs
          Extras
          Frontend/Docs
          Frontend/implementations/typescript/node_modules
          Frontend/library/dist
          Frontend/library/node_modules
          Frontend/library/types
          Frontend/ui-library/dist
          Frontend/ui-library/node_modules
          Frontend/ui-library/types
          SFU/Docs
          SFU/node_modules
          Signalling/build
          Signalling/docs
          Signalling/node_modules
          SignallingWebServer/build
          SignallingWebServer/node_modules
          SS_Test

    - name: Archive Release .zip
      uses: thedoctor0/zip-release@0.7.1
      with:
        directory: '.'
        path: >-
          PixelStreamingInfrastructure-${{ github.ref_name }}-${{ steps.getversion.outputs.version }}/Common
          PixelStreamingInfrastructure-${{ github.ref_name }}-${{ steps.getversion.outputs.version }}/Signalling
        type: 'zip'
        filename: '${{ github.ref_name }}-${{ steps.getversion.outputs.version }}.zip'
        exclusions: ''

    - name: "Make the release"
      uses: ncipollo/release-action@v1
      with:
        tag: "${{ github.ref_name }}-${{ steps.getversion.outputs.version }}"
        artifacts: "${{ github.ref_name }}-${{ steps.getversion.outputs.version }}.zip,${{ github.ref_name }}-${{ steps.getversion.outputs.version }}.tar.gz"
        generateReleaseNotes: true
